export const PHRASES = [
  "Purple Rock Scissors",
  "PRPL",
  "PRPL-X",
  "Bobby",
  "Orlando Florida",
  "Church Street",
  "downtown",
  "816 W Church St",
  "32805",
  "commit explore do great work",
  "people come first",
  "IoT",
  "wearables",
  "digital",
  "experiential",
  "digital agency",
  "strategic creative agency",
  "innovative solutions",
  "dynamic branding",
  "cutting-edge technology",
  "web design",
  "user-centric design",
  "agile development",
  "data-driven insights",
  "seamless integration",
  "holistic approach",
  "collaborative", "team",
  "disruptive innovation",
  "customer-centric",
  "value proposition",
  "market penetration",
  "thought leadership",
  "brand equity",
  "digital transformation",
  "cross-functional team",
  "scalable solutions",
  "technology stack",
  "cloud computing",
  "artificial intelligence",
  "machine learning",
  "big data analytics",
  "blockchain technology",
  "internet of things",
  "augmented reality",
  "virtual reality",
  "mixed reality",
  "user interface",
  "user experience",
  "responsive design",
  "mobile-first",
  "search engine optimization",
  "content marketing",
  "innovation",
  "digital touchpoint",
  "high-impact projects",
  "web development",
  "software development",
  "mobile applications",
  "e-commerce solutions",
  "state-of-the-art tools",
  "brand identity",
  "visual storytelling",
  "creative strategy",
  "social media marketing",
  "influencer marketing",
  "customer engagement",
  "brand loyalty",
  "customer journey",
  "user acquisition",
  "lead generation",
  "conversion rate optimization",
  "performance marketing",
  "return on investment",
  "key performance indicators",
  "technology at our core",
  "data-driven decisions",
  "intuitive design",
  "cloud hosted",
  "headless CMS",
  "content management system",
  "API",
  "React",
  "NextJS",
  "enterprise website"
];